{{- if .Values.hpa.enabled }}
---
{{- if .Values.analytics.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hms-phase3.fullname" . }}-analytics-hpa
  namespace: analytics-system
  labels:
    {{- include "hms-phase3.labels" . | nindent 4 }}
    component: analytics
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hms-phase3.fullname" . }}-analytics
  minReplicas: {{ .Values.hpa.analytics.minReplicas }}
  maxReplicas: {{ .Values.hpa.analytics.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.analytics.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.analytics.targetMemoryUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 10
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 60
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
---
{{- end }}
{{- if .Values.mobile.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hms-phase3.fullname" . }}-mobile-hpa
  namespace: mobile-system
  labels:
    {{- include "hms-phase3.labels" . | nindent 4 }}
    component: mobile
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hms-phase3.fullname" . }}-mobile
  minReplicas: {{ .Values.hpa.mobile.minReplicas }}
  maxReplicas: {{ .Values.hpa.mobile.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.mobile.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.mobile.targetMemoryUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 600
      policies:
      - type: Percent
        value: 20
        periodSeconds: 120
    scaleUp:
      stabilizationWindowSeconds: 120
      policies:
      - type: Percent
        value: 100
        periodSeconds: 60
---
{{- end }}
{{- if .Values.security.rbac.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "hms-phase3.fullname" . }}-rbac-hpa
  namespace: security-system
  labels:
    {{- include "hms-phase3.labels" . | nindent 4 }}
    component: rbac
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "hms-phase3.fullname" . }}-rbac
  minReplicas: {{ .Values.hpa.rbac.minReplicas }}
  maxReplicas: {{ .Values.hpa.rbac.maxReplicas }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.hpa.rbac.targetCPUUtilizationPercentage }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 900
      policies:
      - type: Percent
        value: 25
        periodSeconds: 300
    scaleUp:
      stabilizationWindowSeconds: 180
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
{{- end }}
{{- end }}