export enum ReportType {
  PATIENT_SUMMARY = 'PATIENT_SUMMARY',
  DEPARTMENT_PERFORMANCE = 'DEPARTMENT_PERFORMANCE',
  FINANCIAL_SUMMARY = 'FINANCIAL_SUMMARY',
  INVENTORY_STATUS = 'INVENTORY_STATUS',
  STAFF_PERFORMANCE = 'STAFF_PERFORMANCE',
  APPOINTMENT_ANALYTICS = 'APPOINTMENT_ANALYTICS',
  LAB_RESULTS_SUMMARY = 'LAB_RESULTS_SUMMARY',
  RADIOLOGY_REPORTS = 'RADIOLOGY_REPORTS',
  PHARMACY_DISPENSATION = 'PHARMACY_DISPENSATION',
  EMERGENCY_RESPONSE = 'EMERGENCY_RESPONSE',
  SURGERY_OUTCOMES = 'SURGERY_OUTCOMES',
  IPD_ADMISSION_SUMMARY = 'IPD_ADMISSION_SUMMARY',
  BLOOD_BANK_INVENTORY = 'BLOOD_BANK_INVENTORY',
  COMPLIANCE_AUDIT = 'COMPLIANCE_AUDIT',
}

export enum ReportFormat {
  PDF = 'PDF',
  EXCEL = 'EXCEL',
  CSV = 'CSV',
  JSON = 'JSON',
}

export enum ReportStatus {
  PENDING = 'PENDING',
  GENERATING = 'GENERATING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}
