apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: ultimate-hms
  labels:
    app: vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault-auth
      containers:
      - name: vault
        image: hashicorp/vault:1.15
        ports:
        - containerPort: 8200
          name: vault-port
        env:
        - name: VAULT_ADDR
          value: "http://0.0.0.0:8200"
        - name: VAULT_API_ADDR
          value: "http://0.0.0.0:8200"
        - name: VAULT_CLUSTER_ADDR
          value: "https://vault:8201"
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: "root"
        - name: VAULT_DEV_LISTEN_ADDRESS
          value: "0.0.0.0:8200"
        volumeMounts:
        - name: vault-data
          mountPath: /vault/data
        - name: vault-config
          mountPath: /vault/config
        - name: vault-logs
          mountPath: /vault/logs
        securityContext:
          capabilities:
            add: ["IPC_LOCK"]
      volumes:
      - name: vault-data
        persistentVolumeClaim:
          claimName: vault-pvc
      - name: vault-config
        configMap:
          name: vault-config
      - name: vault-logs
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: ultimate-hms
  labels:
    app: vault
spec:
  selector:
    app: vault
  ports:
  - name: vault
    port: 8200
    targetPort: 8200
  type: ClusterIP
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-config
  namespace: ultimate-hms
data:
  vault.hcl: |
    storage "file" {
      path = "/vault/data"
    }
    listener "tcp" {
      address = "0.0.0.0:8200"
      tls_disable = 1
    }
    seal "transit" {
      address = "https://hsm.example.com:8200"
      token = "s-xxxxxxxx"
      key_name = "unseal-key"
      mount_path = "transit/"
    }
    ui = true
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-pvc
  namespace: ultimate-hms
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-auth
  namespace: ultimate-hms
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-auth-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-auth-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-auth-role
subjects:
- kind: ServiceAccount
  name: vault-auth
  namespace: ultimate-hms