---
# GraphQL API Layer - Unified Service Access
# Phase 2B: API Layer & Integration - Week 2
apiVersion: v1
kind: Namespace
metadata:
  name: graphql-system
  labels:
    app: hospital-management-system
    component: api
    system: graphql
    phase: phase2

---
# GraphQL ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: graphql-config
  namespace: graphql-system
  labels:
    app: hospital-management-system
    component: api
    system: graphql
data:
  OPENMRS_API_URL: "http://openmrs.openmrs-system.svc.cluster.local"
  METASFRESH_API_URL: "http://metasfresh-backend.metasfresh-system.svc.cluster.local"
  REDIS_URL: "redis://redis.graphql-system.svc.cluster.local:6379"
  ELASTICSEARCH_URL: "http://elasticsearch-hms.ultimate-hms.svc.cluster.local:9200"
  DATABASE_HOST: "postgresql-hms.ultimate-hms.svc.cluster.local"
  DATABASE_PORT: "5432"
  DATABASE_NAME: "hms_db"
  DEFAULT_SCHEMA: "public"

