---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hms-grafana-dashboard
  namespace: monitoring
  labels:
    app: hospital-management-system
    component: monitoring
data:
  hms-overview.json: |
    {
      "dashboard": {
        "id": null,
        "title": "Ultimate HMS Overview",
        "tags": ["hms", "healthcare", "monitoring"],
        "timezone": "browser",
        "panels": [
          {
            "id": 1,
            "title": "Database Status",
            "type": "stat",
            "targets": [
              {
                "expr": "up{job=\"hms-services\", component=\"database\"}",
                "legendFormat": "{{system}}"
              }
            ],
            "fieldConfig": {
              "defaults": {
                "mappings": [
                  {
                    "options": {
                      "0": {
                        "text": "DOWN",
                        "color": "red"
                      },
                      "1": {
                        "text": "UP",
                        "color": "green"
                      }
                    },
                    "type": "value"
                  }
                ]
              }
            },
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 0
            }
          },
          {
            "id": 2,
            "title": "Pod Restarts",
            "type": "table",
            "targets": [
              {
                "expr": "kube_pod_container_status_restarts_total{namespace=\"ultimate-hms\"}",
                "legendFormat": "{{pod}}"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 0
            }
          },
          {
            "id": 3,
            "title": "CPU Usage by Service",
            "type": "graph",
            "targets": [
              {
                "expr": "rate(container_cpu_usage_seconds_total{namespace=\"ultimate-hms\"}[5m]) * 100",
                "legendFormat": "{{pod}}"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 0,
              "y": 8
            }
          },
          {
            "id": 4,
            "title": "Memory Usage by Service",
            "type": "graph",
            "targets": [
              {
                "expr": "container_memory_usage_bytes{namespace=\"ultimate-hms\"} / 1024 / 1024",
                "legendFormat": "{{pod}}"
              }
            ],
            "gridPos": {
              "h": 8,
              "w": 12,
              "x": 12,
              "y": 8
            }
          }
        ],
        "time": {
          "from": "now-1h",
          "to": "now"
        },
        "timepicker": {},
        "templating": {
          "list": []
        },
        "annotations": {
          "list": []
        },
        "refresh": "30s",
        "schemaVersion": 27,
        "version": 0,
        "links": []
      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: hms-grafana-provisioning
  namespace: monitoring
  labels:
    app: hospital-management-system
    component: monitoring
data:
  dashboards.yml: |
    apiVersion: 1
    providers:
    - name: 'HMS Dashboards'
      type: file
      disableDeletion: false
      updateIntervalSeconds: 10
      allowUiUpdates: true
      options:
        path: /var/lib/grafana/dashboards/hms

  datasources.yml: |
    apiVersion: 1
    datasources:
    - name: HMS-Prometheus
      type: prometheus
      access: proxy
      url: http://prometheus-kube-prometheus-prometheus.monitoring.svc.cluster.local:9090
      isDefault: false
      editable: true