# Production environment patches
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: graphql-api
# spec:
#   template:
#     spec:
#       containers:
#       - name: graphql-api
#         env:
#         - name: NODE_ENV
#           value: "production"
#         - name: LOG_LEVEL
#           value: "warn"
# ---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: analytics-service
  namespace: analytics-system
spec:
  template:
    spec:
      containers:
      - name: analytics
        env:
        - name: NODE_ENV
          value: "production"
        - name: LOG_LEVEL
          value: "info"